import { Strain } from './types';

export const STRAINS: Record<string, Strain> = {
  'purple_haze': {
    id: 'purple_haze',
    name: 'Purple Haze',
    type: 'Sativa',
    description: 'Un legendario híbrido de dominancia sativa conocido por sus efectos eufóricos y soñadores y su vibrante coloración púrpura durante la floración tardía. Un cultivo moderadamente desafiante pero gratificante.',
    cost: 15,
    visuals: {
      leafColor: '#8A2BE2',
      budColor: '#9400D3',
      stemColor: '#5C4033',
      leafShape: 'Sativa',
      pistilColor: '#FFFFFF', 
      pistilMaturationColor: '#FFA500', // White to Orange
      frostiness: 0.8,
      budStructure: 'airy',
      leafSerration: 1.2,
      branchingPattern: 'alternate',
      colaShape: 'spear',
      colorationTriggers: [
        { stageIndex: 12, leafColor: '#6a0dad' },
        { stageIndex: 14, leafColor: '#4b0082', budColor: '#483d8b' }
      ],
      environmentalVisuals: {
        tempLowTrigger: {
            temp: 18,
            leafColor: '#4b0082',
            budColor: '#2e0854'
        },
        nutrientDeficiency: { level: 40, leafColor: '#b8a642' },
        nutrientToxicity: { level: 95, leafColor: '#004d00' }
      },
    },
    growth: {
      heightFactor: 1.1,
      widthFactor: 0.9,
      nutrientUptake: 1.2,
      waterUptake: 2.0,
      yieldFactor: 1.0,
    },
    environment: {
      optimalTemp: [20, 28],
      optimalHumidity: [50, 60],
    },
  },
  'northern_lights': {
    id: 'northern_lights',
    name: 'Northern Lights',
    type: 'Indica',
    description: 'Una índica pura apreciada por sus cogollos resinosos y su resistencia. Famosa por su rápida floración y efectos relajantes, lo que la convierte en una favorita para principiantes y cultivadores experimentados.',
    cost: 10,
    visuals: {
      leafColor: '#006400',
      budColor: '#7CFC00',
      stemColor: '#5C4033',
      leafShape: 'Indica',
      pistilColor: '#FFFFFF',
      pistilMaturationColor: '#D2691E',
      frostiness: 0.9,
      budStructure: 'dense',
      leafSerration: 0.9,
      branchingPattern: 'opposite',
      colaShape: 'round',
      environmentalVisuals: {
        nutrientDeficiency: { level: 35, leafColor: '#cccc33' }
      },
    },
    growth: {
      heightFactor: 0.8,
      widthFactor: 1.2,
      nutrientUptake: 1.5,
      waterUptake: 1.8,
      yieldFactor: 1.3,
    },
    environment: {
      optimalTemp: [18, 26],
      optimalHumidity: [45, 55],
    },
  },
  'sour_diesel': {
    id: 'sour_diesel',
    name: 'Sour Diesel',
    type: 'Sativa',
    description: 'Una sativa vigorizante con un distintivo aroma a diésel. Conocida por sus efectos cerebrales de acción rápida y energizantes, esta es una variedad de crecimiento alto que requiere algo de espacio.',
    cost: 20,
    visuals: {
      leafColor: '#9ACD32',
      budColor: '#ADFF2F',
      stemColor: '#6B4226',
      leafShape: 'Sativa',
      pistilColor: '#FFD700',
      pistilMaturationColor: '#FF4500',
      frostiness: 0.7,
      budStructure: 'airy',
      leafSerration: 1.4,
      branchingPattern: 'alternate',
      colaShape: 'spear',
    },
    growth: {
      heightFactor: 1.4,
      widthFactor: 0.8,
      nutrientUptake: 1.3,
      waterUptake: 2.2,
      yieldFactor: 1.1,
    },
    environment: {
      optimalTemp: [22, 30],
      optimalHumidity: [55, 65],
    },
  },
  'granddaddy_purple': {
    id: 'granddaddy_purple',
    name: 'Granddaddy Purple',
    type: 'Indica',
    description: 'Una índica icónica de California con profundos matices púrpuras. Famosa por su aroma a uva y bayas, y sus efectos profundamente relajantes. Cogollos compactos y muy resinosos.',
    cost: 22,
    visuals: {
      leafColor: '#2E8B57',
      budColor: '#8A2BE2',
      stemColor: '#5C4033',
      leafShape: 'Indica',
      pistilColor: '#FFA500',
      pistilMaturationColor: '#FF4500',
      frostiness: 0.85,
      budStructure: 'dense',
      leafSerration: 0.8,
      branchingPattern: 'opposite',
      colaShape: 'round',
      colorationTriggers: [
        { stageIndex: 11, leafColor: '#483D8B' },
        { stageIndex: 13, budColor: '#4B0082' }
      ],
      environmentalVisuals: {
        tempLowTrigger: { temp: 19, leafColor: '#3b0062', budColor: '#2c0049' }
      },
    },
    growth: {
      heightFactor: 0.75,
      widthFactor: 1.3,
      nutrientUptake: 1.6,
      waterUptake: 1.7,
      yieldFactor: 1.2,
    },
    environment: {
      optimalTemp: [19, 27],
      optimalHumidity: [40, 50],
    },
  },
  'blue_dream': {
    id: 'blue_dream',
    name: 'Blue Dream',
    type: 'Hybrid',
    description: 'Un híbrido de dominancia sativa legendario por sus efectos equilibrados. Combina una relajación corporal completa con una suave estimulación cerebral. Un gran productor y favorito de muchos.',
    cost: 18,
    visuals: {
      leafColor: '#228B22',
      budColor: '#90EE90',
      stemColor: '#5C4033',
      leafShape: 'Hybrid',
      pistilColor: '#FFFFFF',
      pistilMaturationColor: '#FF8C00',
      frostiness: 0.75,
      budStructure: 'dense',
      leafSerration: 1.1,
      branchingPattern: 'alternate',
      colaShape: 'conical',
      environmentalVisuals: {
        tempLowTrigger: { temp: 20, leafColor: '#1E90FF' }
      },
    },
    growth: {
      heightFactor: 1.2,
      widthFactor: 1.1,
      nutrientUptake: 1.4,
      waterUptake: 2.1,
      yieldFactor: 1.5,
    },
    environment: {
      optimalTemp: [21, 29],
      optimalHumidity: [50, 65],
    },
  },
  'gg4': {
    id: 'gg4',
    name: 'GG4',
    type: 'Hybrid',
    description: 'Anteriormente Gorilla Glue, esta potente cepa híbrida es famosa por su extrema producción de resina que pega los dedos. Proporciona una fuerte euforia y relajación.',
    cost: 25,
    visuals: {
      leafColor: '#556B2F',
      budColor: '#BDB76B',
      stemColor: '#5C4033',
      leafShape: 'Hybrid',
      pistilColor: '#FFFFFF',
      pistilMaturationColor: '#CD853F',
      frostiness: 1.0,
      budStructure: 'dense',
      leafSerration: 1.0,
      branchingPattern: 'opposite',
      colaShape: 'conical',
    },
    growth: {
      heightFactor: 1.0,
      widthFactor: 1.0,
      nutrientUptake: 1.8,
      waterUptake: 1.9,
      yieldFactor: 1.4,
    },
    environment: {
      optimalTemp: [20, 28],
      optimalHumidity: [45, 60],
    },
  },
  'durban_poison': {
    id: 'durban_poison',
    name: 'Durban Poison',
    type: 'Sativa',
    description: 'Una sativa pura sudafricana venerada por su aroma dulce y especiado. Proporciona un efecto energético y edificante, perfecto para la creatividad y las tareas diurnas.',
    cost: 16,
    visuals: {
      leafColor: '#3CB371',
      budColor: '#98FB98',
      stemColor: '#6B4226',
      leafShape: 'Sativa',
      pistilColor: '#F0E68C',
      pistilMaturationColor: '#FFA500',
      frostiness: 0.6,
      budStructure: 'airy',
      leafSerration: 1.5,
      branchingPattern: 'alternate',
      colaShape: 'spear',
    },
    growth: {
      heightFactor: 1.6,
      widthFactor: 0.7,
      nutrientUptake: 1.1,
      waterUptake: 2.4,
      yieldFactor: 0.9,
    },
    environment: {
      optimalTemp: [22, 32],
      optimalHumidity: [55, 70],
    },
  },
  'cosmic_crunch': {
    id: 'cosmic_crunch',
    name: 'Cosmic Crunch',
    type: 'Hybrid',
    description: 'Un híbrido perfectamente equilibrado conocido por sus cogollos brillantes y cubiertos de tricomas y un complejo aroma dulce y terroso. Ofrece una experiencia eufórica pero relajante.',
    cost: 28,
    visuals: {
      leafColor: '#00552e',
      budColor: '#90EE90',
      stemColor: '#5C4033',
      leafShape: 'Hybrid',
      pistilColor: '#FF8C00',
      pistilMaturationColor: '#D2691E',
      frostiness: 0.95,
      budStructure: 'dense',
      leafSerration: 1.1,
      branchingPattern: 'opposite',
      colaShape: 'conical',
      colorationTriggers: [
        { stageIndex: 13, budColor: '#cda4de' }
      ],
    },
    growth: {
      heightFactor: 1.0,
      widthFactor: 1.1,
      nutrientUptake: 1.7,
      waterUptake: 2.0,
      yieldFactor: 1.3,
    },
    environment: {
      optimalTemp: [20, 27],
      optimalHumidity: [45, 55],
    },
  },
  'solar_flare': {
    id: 'solar_flare',
    name: 'Solar Flare',
    type: 'Sativa',
    description: 'Una sativa radiante que crece alta y orgullosa. Famosa por su aroma a cítricos picantes y un subidón edificante y energético que es perfecto para un impulso creativo.',
    cost: 30,
    visuals: {
      leafColor: '#9ACD32',
      budColor: '#ADFF2F',
      stemColor: '#6B4226',
      leafShape: 'Sativa',
      pistilColor: '#FFD700',
      pistilMaturationColor: '#FF4500',
      frostiness: 0.7,
      budStructure: 'airy',
      leafSerration: 1.4,
      branchingPattern: 'alternate',
      colaShape: 'spear',
    },
    growth: {
      heightFactor: 1.5,
      widthFactor: 0.75,
      nutrientUptake: 1.2,
      waterUptake: 2.5,
      yieldFactor: 1.0,
    },
    environment: {
      optimalTemp: [23, 31],
      optimalHumidity: [55, 65],
    },
  },
  'moonshadow_kush': {
    id: 'moonshadow_kush',
    name: 'Moonshadow Kush',
    type: 'Indica',
    description: 'Una índica misteriosa y potente con cogollos oscuros y densos. Tiene un aroma pesado y terroso con matices de pino, lo que conduce a un efecto profundamente tranquilo y sedante, ideal para la noche.',
    cost: 32,
    visuals: {
      leafColor: '#013220',
      budColor: '#556B2F',
      stemColor: '#4A2E1A',
      leafShape: 'Indica',
      pistilColor: '#FF4500',
      pistilMaturationColor: '#8B0000',
      frostiness: 0.9,
      budStructure: 'dense',
      leafSerration: 0.8,
      branchingPattern: 'opposite',
      colaShape: 'round',
      environmentalVisuals: {
        tempLowTrigger: { temp: 18, leafColor: '#2F4F4F', budColor: '#1A2A2A' }
      },
    },
    growth: {
      heightFactor: 0.7,
      widthFactor: 1.4,
      nutrientUptake: 1.9,
      waterUptake: 1.6,
      yieldFactor: 1.4,
    },
    environment: {
      optimalTemp: [18, 25],
      optimalHumidity: [40, 50],
    },
  },
};